export interface Country {
  name: string;
  dial: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: 'Algeria', dial: '+213', flag: '🇩🇿' },
  { name: 'Angola', dial: '+244', flag: '🇦🇴' },
  { name: 'Benin', dial: '+229', flag: '🇧🇯' },
  { name: 'Botswana', dial: '+267', flag: '🇧🇼' },
  { name: 'Burkina Faso', dial: '+226', flag: '🇧🇫' },
  { name: 'Burundi', dial: '+257', flag: '🇧🇮' },
  { name: 'Cabo Verde', dial: '+238', flag: '🇨🇻' },
  { name: 'Cameroon', dial: '+237', flag: '🇨🇲' },
  { name: 'Central African Republic', dial: '+236', flag: '🇨🇫' },
  { name: 'Chad', dial: '+235', flag: '🇹🇩' },
  { name: 'Comoros', dial: '+269', flag: '🇰🇲' },
  { name: 'Congo (Brazzaville)', dial: '+242', flag: '🇨🇬' },
  { name: 'Congo (DRC)', dial: '+243', flag: '🇨🇩' },
  { name: 'Djibouti', dial: '+253', flag: '🇩🇯' },
  { name: 'Egypt', dial: '+20', flag: '🇪🇬' },
  { name: 'Equatorial Guinea', dial: '+240', flag: '🇬🇶' },
  { name: 'Eritrea', dial: '+291', flag: '🇪🇷' },
  { name: 'Eswatini', dial: '+268', flag: '🇸🇿' },
  { name: 'Ethiopia', dial: '+251', flag: '🇪🇹' },
  { name: 'Gabon', dial: '+241', flag: '🇬🇦' },
  { name: 'Gambia', dial: '+220', flag: '🇬🇲' },
  { name: 'Ghana', dial: '+233', flag: '🇬🇭' },
  { name: 'Guinea', dial: '+224', flag: '🇬🇳' },
  { name: 'Guinea-Bissau', dial: '+245', flag: '🇬🇼' },
  { name: 'Ivory Coast', dial: '+225', flag: '🇨🇮' },
  { name: 'Kenya', dial: '+254', flag: '🇰🇪' },
  { name: 'Lesotho', dial: '+266', flag: '🇱🇸' },
  { name: 'Liberia', dial: '+231', flag: '🇱🇷' },
  { name: 'Libya', dial: '+218', flag: '🇱🇾' },
  { name: 'Madagascar', dial: '+261', flag: '🇲🇬' },
  { name: 'Malawi', dial: '+265', flag: '🇲🇼' },
  { name: 'Mali', dial: '+223', flag: '🇲🇱' },
  { name: 'Mauritania', dial: '+222', flag: '🇲🇷' },
  { name: 'Mauritius', dial: '+230', flag: '🇲🇺' },
  { name: 'Morocco', dial: '+212', flag: '🇲🇦' },
  { name: 'Mozambique', dial: '+258', flag: '🇲🇿' },
  { name: 'Namibia', dial: '+264', flag: '🇳🇦' },
  { name: 'Niger', dial: '+227', flag: '🇳🇪' },
  { name: 'Nigeria', dial: '+234', flag: '🇳🇬' },
  { name: 'Rwanda', dial: '+250', flag: '🇷🇼' },
  { name: 'Sao Tome and Principe', dial: '+239', flag: '🇸🇹' },
  { name: 'Senegal', dial: '+221', flag: '🇸🇳' },
  { name: 'Seychelles', dial: '+248', flag: '🇸🇨' },
  { name: 'Sierra Leone', dial: '+232', flag: '🇸🇱' },
  { name: 'Somalia', dial: '+252', flag: '🇸🇴' },
  { name: 'South Africa', dial: '+27', flag: '🇿🇦' },
  { name: 'South Sudan', dial: '+211', flag: '🇸🇸' },
  { name: 'Sudan', dial: '+249', flag: '🇸🇩' },
  { name: 'Tanzania', dial: '+255', flag: '🇹🇿' },
  { name: 'Togo', dial: '+228', flag: '🇹🇬' },
  { name: 'Tunisia', dial: '+216', flag: '🇹🇳' },
  { name: 'Uganda', dial: '+256', flag: '🇺🇬' },
  { name: 'Zambia', dial: '+260', flag: '🇿🇲' },
  { name: 'Zimbabwe', dial: '+263', flag: '🇿🇼' },
];

export const DEFAULT_COUNTRY = COUNTRIES.find((c) => c.name === 'Rwanda')!;
