export type PropertyType = 'Studio' | 'House' | 'Apartment' | 'Villa';

export interface MockProperty {
  id: string;
  title: string;
  district: string;
  price: number;
  beds: number;
  baths: number;
  type: PropertyType;
  rating: number;
  views: number;
  verified: boolean;
  premium: boolean;
  featured: boolean;
  description: string;
}

export const FEATURED_PROPERTIES: MockProperty[] = [
  {
    id: 'feat-1',
    title: 'Gikondo Riverside Apartment',
    district: 'Gikondo',
    price: 420000,
    beds: 2,
    baths: 2,
    type: 'Apartment',
    rating: 4.8,
    views: 312,
    verified: true,
    premium: true,
    featured: true,
    description:
      'A bright, riverside apartment in Gikondo with two spacious bedrooms, modern finishes, and easy access to the city center. Ideal for young professionals or small families.',
  },
  {
    id: 'feat-2',
    title: 'Kicukiro Family House',
    district: 'Kicukiro',
    price: 380000,
    beds: 3,
    baths: 2,
    type: 'House',
    rating: 4.6,
    views: 248,
    verified: true,
    premium: false,
    featured: true,
    description:
      'A comfortable three-bedroom family house in a quiet Kicukiro neighborhood, featuring a private compound, ample parking, and proximity to schools and markets.',
  },
  {
    id: 'feat-3',
    title: 'Kimihurura Executive Villa',
    district: 'Kimihurura',
    price: 1200000,
    beds: 4,
    baths: 4,
    type: 'Villa',
    rating: 4.9,
    views: 521,
    verified: true,
    premium: true,
    featured: true,
    description:
      'A luxurious four-bedroom executive villa in upscale Kimihurura, offering premium finishes, a landscaped garden, and 24-hour security in a prestigious, well-connected neighborhood.',
  },
  {
    id: 'feat-4',
    title: 'Nyarutarama Garden Apartment',
    district: 'Nyarutarama',
    price: 280000,
    beds: 2,
    baths: 1,
    type: 'Apartment',
    rating: 4.5,
    views: 187,
    verified: true,
    premium: true,
    featured: false,
    description:
      'A cozy two-bedroom apartment surrounded by mature gardens in Nyarutarama, close to the golf course and embassies, perfect for those seeking a peaceful upscale lifestyle.',
  },
  {
    id: 'feat-5',
    title: 'Gasabo Studio Apartment',
    district: 'Gasabo',
    price: 150000,
    beds: 1,
    baths: 1,
    type: 'Studio',
    rating: 4.3,
    views: 156,
    verified: true,
    premium: false,
    featured: false,
    description:
      'An affordable, well-maintained studio apartment in Gasabo, great for students or single professionals looking for a compact and convenient home close to public transport.',
  },
  {
    id: 'feat-6',
    title: 'Kanombe 2-Bedroom House',
    district: 'Kanombe',
    price: 350000,
    beds: 2,
    baths: 2,
    type: 'House',
    rating: 4.4,
    views: 203,
    verified: true,
    premium: false,
    featured: true,
    description:
      'A practical two-bedroom house in Kanombe, conveniently located near the airport and major roads, with a fenced yard and reliable water and power supply.',
  },
];

export const CATALOG_PROPERTIES: MockProperty[] = [
  {
    id: 'cat-1',
    title: 'Gikondo Modern Studio',
    district: 'Gikondo',
    price: 420000,
    beds: 1,
    baths: 1,
    type: 'Studio',
    rating: 4.5,
    views: 142,
    verified: true,
    premium: false,
    featured: false,
    description:
      'A modern, newly built studio in Gikondo with quality fittings, ample natural light, and easy access to industrial and commercial areas.',
  },
  {
    id: 'cat-2',
    title: 'Kanombe 2-Bedroom House',
    district: 'Kanombe',
    price: 350000,
    beds: 2,
    baths: 2,
    type: 'House',
    rating: 4.6,
    views: 198,
    verified: true,
    premium: false,
    featured: true,
    description:
      'A spacious two-bedroom house near Kanombe airport, featuring a secure compound, two bathrooms, and a quiet residential setting.',
  },
  {
    id: 'cat-3',
    title: 'Gasabo Studio Apartment',
    district: 'Gasabo',
    price: 150000,
    beds: 1,
    baths: 1,
    type: 'Apartment',
    rating: 4.2,
    views: 96,
    verified: true,
    premium: false,
    featured: false,
    description:
      'A budget-friendly studio apartment in Gasabo, ideal for individuals or couples, with easy access to local shops and public transport.',
  },
  {
    id: 'cat-4',
    title: 'Kagugu 3-Bedroom House',
    district: 'Kagugu',
    price: 650000,
    beds: 3,
    baths: 3,
    type: 'House',
    rating: 4.7,
    views: 264,
    verified: true,
    premium: true,
    featured: false,
    description:
      'An elegant three-bedroom house in Kagugu with three full bathrooms, a private driveway, and a peaceful, well-maintained neighborhood.',
  },
  {
    id: 'cat-5',
    title: 'Kimihurura Executive Villa',
    district: 'Kimihurura',
    price: 1200000,
    beds: 4,
    baths: 4,
    type: 'Villa',
    rating: 4.9,
    views: 521,
    verified: true,
    premium: true,
    featured: true,
    description:
      'A premium four-bedroom villa in Kimihurura with high-end finishes, a private garden, and round-the-clock security, located in one of Kigali’s most sought-after areas.',
  },
  {
    id: 'cat-6',
    title: 'Nyarutarama Apartment',
    district: 'Nyarutarama',
    price: 280000,
    beds: 2,
    baths: 1,
    type: 'Apartment',
    rating: 4.4,
    views: 178,
    verified: true,
    premium: false,
    featured: false,
    description:
      'A well-located two-bedroom apartment in Nyarutarama, close to amenities and surrounded by greenery, suitable for small families or working professionals.',
  },
  {
    id: 'cat-7',
    title: 'Kicukiro Modern Studio',
    district: 'Kicukiro',
    price: 180000,
    beds: 1,
    baths: 1,
    type: 'Studio',
    rating: 4.1,
    views: 87,
    verified: true,
    premium: false,
    featured: false,
    description:
      'A compact, modern studio in Kicukiro with efficient use of space, suited to students or young professionals seeking affordable city living.',
  },
  {
    id: 'cat-8',
    title: 'Remera 2-Bedroom Flat',
    district: 'Remera',
    price: 320000,
    beds: 2,
    baths: 2,
    type: 'Apartment',
    rating: 4.3,
    views: 134,
    verified: true,
    premium: false,
    featured: false,
    description:
      'A comfortable two-bedroom flat in Remera, close to shopping centers and major bus routes, ideal for tenants who want convenience and accessibility.',
  },
  {
    id: 'cat-9',
    title: 'Gisozi Family House',
    district: 'Gisozi',
    price: 480000,
    beds: 3,
    baths: 2,
    type: 'House',
    rating: 4.6,
    views: 211,
    verified: true,
    premium: true,
    featured: false,
    description:
      'A roomy three-bedroom family house in Gisozi, featuring a fenced compound, garden space, and a calm residential setting away from the city noise.',
  },
  {
    id: 'cat-10',
    title: 'Kibagabaga Studio',
    district: 'Kibagabaga',
    price: 200000,
    beds: 1,
    baths: 1,
    type: 'Studio',
    rating: 4.0,
    views: 79,
    verified: true,
    premium: false,
    featured: false,
    description:
      'A simple, affordable studio in Kibagabaga, well-suited for individuals looking for a quiet place close to local schools and markets.',
  },
  {
    id: 'cat-11',
    title: 'Kacyiru Executive Apt',
    district: 'Kacyiru',
    price: 550000,
    beds: 2,
    baths: 2,
    type: 'Apartment',
    rating: 4.8,
    views: 289,
    verified: true,
    premium: true,
    featured: false,
    description:
      'An executive two-bedroom apartment in Kacyiru, near government offices and embassies, offering modern finishes and a secure building entrance.',
  },
  {
    id: 'cat-12',
    title: 'Butamwa House',
    district: 'Butamwa',
    price: 290000,
    beds: 3,
    baths: 2,
    type: 'House',
    rating: 4.2,
    views: 103,
    verified: true,
    premium: false,
    featured: false,
    description:
      'A spacious three-bedroom house in Butamwa offering a quieter, more affordable alternative to central Kigali, with plenty of outdoor space for families.',
  },
];
